# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import grpc_pb2 as grpc__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecondaryChannelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Secondary_media_manager = channel.unary_unary(
                '/SecondaryChannel/Secondary_media_manager',
                request_serializer=grpc__pb2.SecondaryData.SerializeToString,
                response_deserializer=grpc__pb2.TextChunk.FromString,
                _registered_method=True)


class SecondaryChannelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Secondary_media_manager(self, request, context):
        """Secondary channel request moved here
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecondaryChannelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Secondary_media_manager': grpc.unary_unary_rpc_method_handler(
                    servicer.Secondary_media_manager,
                    request_deserializer=grpc__pb2.SecondaryData.FromString,
                    response_serializer=grpc__pb2.TextChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SecondaryChannel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SecondaryChannel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecondaryChannel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Secondary_media_manager(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SecondaryChannel/Secondary_media_manager',
            grpc__pb2.SecondaryData.SerializeToString,
            grpc__pb2.TextChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MediaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessAudioImg = channel.unary_stream(
                '/MediaService/ProcessAudioImg',
                request_serializer=grpc__pb2.AudioImgRequest.SerializeToString,
                response_deserializer=grpc__pb2.TextChunk.FromString,
                _registered_method=True)
        self.StreamImages = channel.stream_unary(
                '/MediaService/StreamImages',
                request_serializer=grpc__pb2.ImageStreamRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetBbox = channel.unary_unary(
                '/MediaService/GetBbox',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=grpc__pb2.FaceBoundingBox.FromString,
                _registered_method=True)
        self.ClearQueue = channel.unary_unary(
                '/MediaService/ClearQueue',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=grpc__pb2.QueueRemoval.FromString,
                _registered_method=True)


class MediaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessAudioImg(self, request, context):
        """RPC method to send audio and image data together
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamImages(self, request_iterator, context):
        """RPC method to handle image streams
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBbox(self, request, context):
        """RPC method to get face detections bboxes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearQueue(self, request, context):
        """RPC method to clear out the llama and image queue
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessAudioImg': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessAudioImg,
                    request_deserializer=grpc__pb2.AudioImgRequest.FromString,
                    response_serializer=grpc__pb2.TextChunk.SerializeToString,
            ),
            'StreamImages': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamImages,
                    request_deserializer=grpc__pb2.ImageStreamRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBbox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBbox,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=grpc__pb2.FaceBoundingBox.SerializeToString,
            ),
            'ClearQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearQueue,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=grpc__pb2.QueueRemoval.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MediaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MediaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessAudioImg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MediaService/ProcessAudioImg',
            grpc__pb2.AudioImgRequest.SerializeToString,
            grpc__pb2.TextChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamImages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/MediaService/StreamImages',
            grpc__pb2.ImageStreamRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MediaService/GetBbox',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            grpc__pb2.FaceBoundingBox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MediaService/ClearQueue',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            grpc__pb2.QueueRemoval.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SpeakerRecognitionServiceStub(object):
    """============ Speaker Recognition (Phase 1) ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeSpeakers = channel.stream_stream(
                '/SpeakerRecognitionService/RecognizeSpeakers',
                request_serializer=grpc__pb2.SpeakerAudioSegment.SerializeToString,
                response_deserializer=grpc__pb2.SpeakerResult.FromString,
                _registered_method=True)
        self.ProcessVideo = channel.stream_stream(
                '/SpeakerRecognitionService/ProcessVideo',
                request_serializer=grpc__pb2.VideoUploadChunk.SerializeToString,
                response_deserializer=grpc__pb2.VideoDownloadChunk.FromString,
                _registered_method=True)


class SpeakerRecognitionServiceServicer(object):
    """============ Speaker Recognition (Phase 1) ============

    """

    def RecognizeSpeakers(self, request_iterator, context):
        """Bidirectional streaming: client sends VAD audio segments,
        server returns speaker identification results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessVideo(self, request_iterator, context):
        """Batch video processing: client uploads video, server annotates and sends back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeakerRecognitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeSpeakers': grpc.stream_stream_rpc_method_handler(
                    servicer.RecognizeSpeakers,
                    request_deserializer=grpc__pb2.SpeakerAudioSegment.FromString,
                    response_serializer=grpc__pb2.SpeakerResult.SerializeToString,
            ),
            'ProcessVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessVideo,
                    request_deserializer=grpc__pb2.VideoUploadChunk.FromString,
                    response_serializer=grpc__pb2.VideoDownloadChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SpeakerRecognitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SpeakerRecognitionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeakerRecognitionService(object):
    """============ Speaker Recognition (Phase 1) ============

    """

    @staticmethod
    def RecognizeSpeakers(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/SpeakerRecognitionService/RecognizeSpeakers',
            grpc__pb2.SpeakerAudioSegment.SerializeToString,
            grpc__pb2.SpeakerResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/SpeakerRecognitionService/ProcessVideo',
            grpc__pb2.VideoUploadChunk.SerializeToString,
            grpc__pb2.VideoDownloadChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
